services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "//free2code.nomorepartiesco.ru/api/afisha"
        VITE_CDN_URL: "//free2code.nomorepartiesco.ru/content/afisha"
    container_name: frontend
    networks:
      - webnet
    volumes:
      - frontend_dist:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - webnet
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=prac
      - DATABASE_USERNAME=prac
      - DATABASE_PASSWORD=prac
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./initDB/:/docker-entrypoint-initdb.d
      - postgres_data:/usr/local/pgsql/data
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - webnet
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=veseliy.koteika@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=postgres

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - frontend_dist:/var/www/frontend:rw
      - ./backend/public/content:/var/www/frontend/content:rw

  certbot:
    image: certbot/certbot:latest
    networks:
      - webnet
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  frontend_dist:

networks:
  webnet:

